import { sql } from "drizzle-orm";
import {
  boolean,
  date,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  time,
  timestamp,
} from "drizzle-orm/pg-core";
import type { SyncResource, SyncStage } from "../sync";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
};

export const ddfProperties = pgTable(
  "ddf_properties",
  {
    listingKey: text("listing_key").primaryKey(),
    listingId: text("listing_id"),
    modificationTimestamp: timestamp("modification_timestamp", { withTimezone: true }),
    originalEntryTimestamp: timestamp("original_entry_timestamp", { withTimezone: true }),
    availabilityDate: date("availability_date"),
    statusChangeTimestamp: timestamp("status_change_timestamp", { withTimezone: true }),
    photosChangeTimestamp: timestamp("photos_change_timestamp", { withTimezone: true }),
    standardStatus: text("standard_status"),
    propertySubType: text("property_sub_type"),
    businessType: jsonb("business_type").$type<unknown>(),
    propertyType: text("property_type"),
    publicRemarks: text("public_remarks"),
    listPrice: doublePrecision("list_price"),
    leaseAmount: doublePrecision("lease_amount"),
    leaseAmountFrequency: text("lease_amount_frequency"),
    leasePerUnit: text("lease_per_unit"),
    pricePerUnit: doublePrecision("price_per_unit"),
    associationFee: doublePrecision("association_fee"),
    associationFeeFrequency: text("association_fee_frequency"),
    associationName: text("association_name"),
    associationFeeIncludes: jsonb("association_fee_includes").$type<unknown>(),
    totalActualRent: doublePrecision("total_actual_rent"),
    existingLeaseType: jsonb("existing_lease_type").$type<unknown>(),
    listOfficeKey: text("list_office_key"),
    coListOfficeKey: text("co_list_office_key"),
    coListOfficeKey2: text("co_list_office_key2"),
    coListOfficeKey3: text("co_list_office_key3"),
    listAgentKey: text("list_agent_key"),
    coListAgentKey: text("co_list_agent_key"),
    coListAgentKey2: text("co_list_agent_key2"),
    coListAgentKey3: text("co_list_agent_key3"),
    listingUrl: text("listing_url"),
    originatingSystemName: text("originating_system_name"),
    photosCount: integer("photos_count"),
    commonInterest: text("common_interest"),
    listAor: text("list_aor"),
    listAorKey: text("list_aor_key"),
    unparsedAddress: text("unparsed_address"),
    postalCode: text("postal_code"),
    subdivisionName: text("subdivision_name"),
    province: text("province"),
    streetDirPrefix: text("street_dir_prefix"),
    streetDirSuffix: text("street_dir_suffix"),
    streetName: text("street_name"),
    streetNumber: text("street_number"),
    streetSuffix: text("street_suffix"),
    unitNumber: text("unit_number"),
    country: text("country"),
    city: text("city"),
    directions: text("directions"),
    cityRegion: text("city_region"),
    latitude: doublePrecision("latitude"),
    longitude: doublePrecision("longitude"),
    mapCoordinateVerified: boolean("map_coordinate_verified"),
    geocodeManual: boolean("geocode_manual"),
    parkingTotal: integer("parking_total"),
    parkingFeatures: jsonb("parking_features").$type<unknown>(),
    yearBuilt: integer("year_built"),
    bathroomsPartial: integer("bathrooms_partial"),
    bathroomsTotalInteger: integer("bathrooms_total_integer"),
    bedroomsTotal: integer("bedrooms_total"),
    bedroomsAboveGrade: integer("bedrooms_above_grade"),
    bedroomsBelowGrade: integer("bedrooms_below_grade"),
    buildingAreaTotal: doublePrecision("building_area_total"),
    buildingAreaUnits: text("building_area_units"),
    buildingFeatures: jsonb("building_features").$type<unknown>(),
    aboveGradeFinishedArea: doublePrecision("above_grade_finished_area"),
    aboveGradeFinishedAreaUnits: text("above_grade_finished_area_units"),
    aboveGradeFinishedAreaSource: text("above_grade_finished_area_source"),
    aboveGradeFinishedAreaMinimum: doublePrecision("above_grade_finished_area_minimum"),
    aboveGradeFinishedAreaMaximum: doublePrecision("above_grade_finished_area_maximum"),
    belowGradeFinishedArea: doublePrecision("below_grade_finished_area"),
    belowGradeFinishedAreaUnits: text("below_grade_finished_area_units"),
    belowGradeFinishedAreaSource: text("below_grade_finished_area_source"),
    belowGradeFinishedAreaMinimum: doublePrecision("below_grade_finished_area_minimum"),
    belowGradeFinishedAreaMaximum: doublePrecision("below_grade_finished_area_maximum"),
    livingArea: doublePrecision("living_area"),
    livingAreaUnits: text("living_area_units"),
    livingAreaSource: text("living_area_source"),
    livingAreaMinimum: doublePrecision("living_area_minimum"),
    livingAreaMaximum: doublePrecision("living_area_maximum"),
    firePlacesTotal: integer("fireplaces_total"),
    fireplace: boolean("fireplace"),
    fireplaceFeatures: jsonb("fireplace_features").$type<unknown>(),
    architecturalStyle: jsonb("architectural_style").$type<unknown>(),
    heating: jsonb("heating").$type<unknown>(),
    foundationDetails: jsonb("foundation_details").$type<unknown>(),
    basement: jsonb("basement").$type<unknown>(),
    exteriorFeatures: jsonb("exterior_features").$type<unknown>(),
    flooring: jsonb("flooring").$type<unknown>(),
    cooling: jsonb("cooling").$type<unknown>(),
    propertyCondition: jsonb("property_condition").$type<unknown>(),
    roof: jsonb("roof").$type<unknown>(),
    constructionMaterials: jsonb("construction_materials").$type<unknown>(),
    stories: integer("stories"),
    propertyAttached: boolean("property_attached"),
    accessibilityFeatures: jsonb("accessibility_features").$type<unknown>(),
    zoning: text("zoning"),
    zoningDescription: text("zoning_description"),
    taxAnnualAmount: doublePrecision("tax_annual_amount"),
    taxBlock: text("tax_block"),
    taxLot: text("tax_lot"),
    taxYear: integer("tax_year"),
    structureType: jsonb("structure_type").$type<unknown>(),
    parcelNumber: text("parcel_number"),
    utilities: jsonb("utilities").$type<unknown>(),
    irrigationSource: jsonb("irrigation_source").$type<unknown>(),
    waterSource: jsonb("water_source").$type<unknown>(),
    sewer: jsonb("sewer").$type<unknown>(),
    electric: jsonb("electric").$type<unknown>(),
    documentsAvailable: jsonb("documents_available").$type<unknown>(),
    waterBodyName: text("water_body_name"),
    view: jsonb("view").$type<unknown>(),
    numberOfBuildings: integer("number_of_buildings"),
    numberOfUnitsTotal: integer("number_of_units_total"),
    lotFeatures: jsonb("lot_features").$type<unknown>(),
    lotSizeArea: doublePrecision("lot_size_area"),
    lotSizeDimensions: text("lot_size_dimensions"),
    lotSizeUnits: text("lot_size_units"),
    poolFeatures: jsonb("pool_features").$type<unknown>(),
    roadSurfaceType: jsonb("road_surface_type").$type<unknown>(),
    currentUse: jsonb("current_use").$type<unknown>(),
    possibleUse: jsonb("possible_use").$type<unknown>(),
    anchorsCoTenants: text("anchors_co_tenants"),
    waterfrontFeatures: jsonb("waterfront_features").$type<unknown>(),
    communityFeatures: jsonb("community_features").$type<unknown>(),
    frontageLengthNumeric: doublePrecision("frontage_length_numeric"),
    frontageLengthNumericUnits: text("frontage_length_numeric_units"),
    fencing: jsonb("fencing").$type<unknown>(),
    appliances: jsonb("appliances").$type<unknown>(),
    otherEquipment: jsonb("other_equipment").$type<unknown>(),
    securityFeatures: jsonb("security_features").$type<unknown>(),
    inclusions: text("inclusions"),
    internetEntireListingDisplay: boolean("internet_entire_listing_display"),
    internetAddressDisplay: boolean("internet_address_display"),
    active: boolean("active").default(true).notNull(),
    raw: jsonb("raw").$type<unknown>().notNull(),
    ...timestamps,
  },
  (table) => [
    index("ddf_properties_modified_idx").on(table.modificationTimestamp),
    index("ddf_properties_list_office_idx").on(table.listOfficeKey),
    index("ddf_properties_list_agent_idx").on(table.listAgentKey),
    index("ddf_properties_status_idx").on(table.standardStatus),
    index("ddf_properties_location_idx").on(table.province, table.city),
    index("ddf_properties_listing_id_idx").on(table.listingId),
  ],
);

export const ddfPropertyRooms = pgTable(
  "ddf_property_rooms",
  {
    roomKey: text("room_key").primaryKey(),
    listingKey: text("listing_key").notNull(),
    listingId: text("listing_id"),
    modificationTimestamp: timestamp("modification_timestamp", { withTimezone: true }),
    roomDescription: text("room_description"),
    roomDimensions: text("room_dimensions"),
    roomLength: doublePrecision("room_length"),
    roomLevel: text("room_level"),
    roomWidth: doublePrecision("room_width"),
    roomLengthWidthUnits: text("room_length_width_units"),
    roomType: text("room_type"),
    raw: jsonb("raw").$type<unknown>().notNull(),
    ...timestamps,
  },
  (table) => [index("ddf_property_rooms_listing_idx").on(table.listingKey)],
);

export const ddfMedia = pgTable(
  "ddf_media",
  {
    mediaKey: text("media_key").primaryKey(),
    resource: text("resource").$type<SyncResource>().notNull(),
    resourceKey: text("resource_key").notNull(),
    resourceRecordId: text("resource_record_id"),
    resourceRecordKey: text("resource_record_key"),
    resourceName: text("resource_name"),
    modificationTimestamp: timestamp("modification_timestamp", { withTimezone: true }),
    mediaUrl: text("media_url"),
    mediaCategory: text("media_category"),
    longDescription: text("long_description"),
    preferredPhoto: boolean("preferred_photo"),
    sortOrder: integer("sort_order"),
    raw: jsonb("raw").$type<unknown>().notNull(),
    ...timestamps,
  },
  (table) => [
    index("ddf_media_owner_idx").on(table.resource, table.resourceKey),
    index("ddf_media_modified_idx").on(table.modificationTimestamp),
  ],
);

export const ddfMembers = pgTable(
  "ddf_members",
  {
    memberKey: text("member_key").primaryKey(),
    memberMlsId: text("member_mls_id"),
    modificationTimestamp: timestamp("modification_timestamp", { withTimezone: true }),
    originalEntryTimestamp: timestamp("original_entry_timestamp", { withTimezone: true }),
    officeKey: text("office_key"),
    officeNationalAssociationId: text("office_national_association_id"),
    jobTitle: text("job_title"),
    memberAorKey: text("member_aor_key"),
    memberAor: text("member_aor"),
    address1: text("address1"),
    address2: text("address2"),
    city: text("city"),
    province: text("province"),
    country: text("country"),
    postalCode: text("postal_code"),
    fax: text("fax"),
    firstName: text("first_name"),
    lastName: text("last_name"),
    middleName: text("middle_name"),
    namePrefix: text("name_prefix"),
    nameSuffix: text("name_suffix"),
    nationalAssociationId: text("national_association_id"),
    nickname: text("nickname"),
    officePhone: text("office_phone"),
    officePhoneExt: text("office_phone_ext"),
    pager: text("pager"),
    tollFreePhone: text("toll_free_phone"),
    status: text("status"),
    type: text("type"),
    email: text("email"),
    emailYn: boolean("email_yn"),
    active: boolean("active").default(true).notNull(),
    raw: jsonb("raw").$type<unknown>().notNull(),
    ...timestamps,
  },
  (table) => [
    index("ddf_members_modified_idx").on(table.modificationTimestamp),
    index("ddf_members_office_idx").on(table.officeKey),
    index("ddf_members_mls_id_idx").on(table.memberMlsId),
  ],
);

export const ddfMemberLanguages = pgTable(
  "ddf_member_languages",
  {
    memberKey: text("member_key").notNull(),
    language: text("language").notNull(),
    ...timestamps,
  },
  (table) => [index("ddf_member_languages_member_idx").on(table.memberKey)],
);

export const ddfMemberDesignations = pgTable(
  "ddf_member_designations",
  {
    memberKey: text("member_key").notNull(),
    designation: text("designation").notNull(),
    ...timestamps,
  },
  (table) => [index("ddf_member_designations_member_idx").on(table.memberKey)],
);

export const ddfSocialMedia = pgTable(
  "ddf_social_media",
  {
    socialMediaKey: text("social_media_key").primaryKey(),
    resource: text("resource").$type<SyncResource>().notNull(),
    resourceKey: text("resource_key").notNull(),
    resourceRecordKey: text("resource_record_key"),
    socialMediaType: text("social_media_type"),
    modificationTimestamp: timestamp("modification_timestamp", { withTimezone: true }),
    resourceName: text("resource_name"),
    socialMediaUrlOrId: text("social_media_url_or_id"),
    raw: jsonb("raw").$type<unknown>().notNull(),
    ...timestamps,
  },
  (table) => [
    index("ddf_social_media_owner_idx").on(table.resource, table.resourceKey),
    index("ddf_social_media_modified_idx").on(table.modificationTimestamp),
  ],
);

export const ddfOffices = pgTable(
  "ddf_offices",
  {
    officeKey: text("office_key").primaryKey(),
    officeMlsId: text("office_mls_id"),
    modificationTimestamp: timestamp("modification_timestamp", { withTimezone: true }),
    originalEntryTimestamp: timestamp("original_entry_timestamp", { withTimezone: true }),
    officeName: text("office_name"),
    officeAorKey: text("office_aor_key"),
    officeAor: text("office_aor"),
    officeNationalAssociationId: text("office_national_association_id"),
    franchiseNationalAssociationId: text("franchise_national_association_id"),
    officeBrokerNationalAssociationId: text("office_broker_national_association_id"),
    address1: text("address1"),
    address2: text("address2"),
    city: text("city"),
    province: text("province"),
    country: text("country"),
    fax: text("fax"),
    phone: text("phone"),
    phoneExt: text("phone_ext"),
    postalCode: text("postal_code"),
    officeType: text("office_type"),
    officeStatus: text("office_status"),
    active: boolean("active").default(true).notNull(),
    raw: jsonb("raw").$type<unknown>().notNull(),
    ...timestamps,
  },
  (table) => [
    index("ddf_offices_modified_idx").on(table.modificationTimestamp),
    index("ddf_offices_location_idx").on(table.province, table.city),
    index("ddf_offices_mls_id_idx").on(table.officeMlsId),
  ],
);

export const ddfOpenHouses = pgTable(
  "ddf_open_houses",
  {
    openHouseKey: text("open_house_key").primaryKey(),
    listingKey: text("listing_key"),
    listingId: text("listing_id"),
    openHouseDate: date("open_house_date"),
    openHouseStartTime: time("open_house_start_time"),
    openHouseEndTime: time("open_house_end_time"),
    openHouseType: text("open_house_type"),
    openHouseStatus: text("open_house_status"),
    openHouseRemarks: text("open_house_remarks"),
    livestreamOpenHouseUrl: text("livestream_open_house_url"),
    raw: jsonb("raw").$type<unknown>().notNull(),
    ...timestamps,
  },
  (table) => [
    index("ddf_open_houses_listing_idx").on(table.listingKey),
    index("ddf_open_houses_listing_id_idx").on(table.listingId),
    index("ddf_open_houses_date_idx").on(table.openHouseDate),
  ],
);

export const ddfWatermarks = pgTable("ddf_watermarks", {
  resource: text("resource").$type<SyncResource>().primaryKey(),
  watermark: text("watermark").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const ddfSyncRuns = pgTable(
  "ddf_sync_runs",
  {
    id: text("id").primaryKey(),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }).notNull(),
    status: text("status").$type<"success" | "partial_failure" | "failed">().notNull(),
    destinationId: integer("destination_id"),
    summary: jsonb("summary").$type<unknown>().notNull(),
  },
  (table) => [index("ddf_sync_runs_started_idx").on(table.startedAt)],
);

export const ddfSyncErrors = pgTable(
  "ddf_sync_errors",
  {
    id: text("id").primaryKey(),
    runId: text("run_id"),
    resource: text("resource").$type<SyncResource>().notNull(),
    recordKey: text("record_key").notNull(),
    stage: text("stage").$type<SyncStage>().notNull(),
    message: text("message").notNull(),
    cause: jsonb("cause").$type<unknown>(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("ddf_sync_errors_run_idx").on(table.runId),
    index("ddf_sync_errors_resource_idx").on(table.resource, table.recordKey),
  ],
);

export const touchUpdatedAt = { updatedAt: sql<Date>`now()` };
