import { Schema } from "effect";
import { MediaSchema } from "./mediaSchema";
import { ODataListEnvelopeSchema } from "./odata";
import { ResourceNameSchema, SocialMediaTypeSchema } from "./officeSchema";

export const MemberSchema = Schema.Struct({
  "@odata.context": Schema.optionalKey(Schema.NullOr(Schema.String)),
  MemberKey: Schema.String,
  MemberMlsId: Schema.Union([Schema.Null, Schema.String]),
  OfficeKey: Schema.Union([Schema.Null, Schema.String]),
  OfficeNationalAssociationId: Schema.Union([Schema.Null, Schema.String]),
  JobTitle: Schema.Union([Schema.Null, Schema.String]),
  MemberAORKey: Schema.Union([Schema.Null, Schema.String]),
  MemberAddress1: Schema.Union([Schema.Null, Schema.String]),
  MemberAddress2: Schema.Union([Schema.Null, Schema.String]),
  MemberFax: Schema.Union([Schema.Null, Schema.String]),
  MemberFirstName: Schema.Union([Schema.Null, Schema.String]),
  MemberLastName: Schema.Union([Schema.Null, Schema.String]),
  MemberMiddleName: Schema.Union([Schema.Null, Schema.String]),
  MemberNamePrefix: Schema.Union([Schema.Null, Schema.String]),
  MemberNameSuffix: Schema.Union([Schema.Null, Schema.String]),
  MemberNationalAssociationId: Schema.Union([Schema.Null, Schema.String]),
  MemberNickname: Schema.Union([Schema.Null, Schema.String]),
  MemberOfficePhone: Schema.Union([Schema.Null, Schema.String]),
  MemberOfficePhoneExt: Schema.Union([Schema.Null, Schema.String]),
  MemberPostalCode: Schema.Union([Schema.Null, Schema.String]),
  MemberPager: Schema.Union([Schema.Null, Schema.String]),
  MemberTollFreePhone: Schema.Union([Schema.Null, Schema.String]),
  ModificationTimestamp: Schema.Union([Schema.Null, Schema.DateTimeUtcFromString]),
  OriginalEntryTimestamp: Schema.Union([Schema.Null, Schema.DateTimeUtcFromString]),
  MemberCity: Schema.Union([Schema.Null, Schema.String]),
  MemberAOR: Schema.Union([
    Schema.Literals([
      "Alberta West",
      "AREA",
      "Barrie",
      "BC Northern",
      "BCREA",
      "Brandon",
      "Brantford",
      "Brooks(South Central Alberta)",
      "Calgary",
      "Centre du Québec",
      "Chatham Kent",
      "Chilliwack",
      "Cornwall",
      "CREA",
      "Central Lakes",
      "Edmonton",
      "Estrie",
      "Fort McMurray",
      "Fraser Valley",
      "Grande Prairie",
      "Greater Vancouver",
      "Cornerstone",
      "Kingston",
      "Lethbridge",
      "Lloydminster",
      "London and St. Thomas",
      "Mauricie",
      "Medicine Hat",
      "APCIQ",
      "MREA",
      "NBREA",
      "Newfoundland & Labrador",
      "Niagara",
      "North Bay",
      "NSAR",
      "Oakville-Milton",
      "Interior REALTORS®",
      "OREA",
      "Ottawa",
      "Outaouais",
      "PEIA",
      "Powell River",
      "Red Deer (Central Alberta)",
      "Renfrew County",
      "Rideau St.Lawrence",
      "New Brunswick",
      "Sarnia",
      "Saskatchewan",
      "Sault Ste. Marie",
      "Sudbury",
      "OnePoint",
      "Thunder Bay",
      "Timmins",
      "Toronto",
      "Vancouver Island",
      "Victoria",
      "Windsor",
      "Winnipeg",
      "Woodstock-Ingersoll-Tillsonburg",
      "Yellowknife",
      "Yukon",
    ]),
    Schema.Null,
  ]),
  MemberCountry: Schema.Union([
    Schema.Literals([
      "Canada",
      "United States of America (the)",
      "Algeria",
      "Afghanistan",
      "Albania",
      "American Samoa",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antigua and Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas (the)",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia (Plurinational State of)",
      "Bonaire, Sint Eustatius and Saba",
      "Bosnia and Herzegovina",
      "Botswana",
      "Bouvet Island",
      "Brazil",
      "British Indian Ocean Territory (the)",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Myanmar",
      "Burundi",
      "Côte d'Ivoire",
      "Cambodia",
      "Cameroon",
      "Cabo Verde",
      "Cayman Islands (the)",
      "Central African Republic (the)",
      "Chad",
      "Chile",
      "China",
      "Christmas Island",
      "Cocos (Keeling) Islands (the)",
      "Colombia",
      "Comoros (the)",
      "Congo (the Democratic Republic of the)",
      "Congo (the)",
      "Cook Islands (the)",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Curaçao",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic (the)",
      "East Timor",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Ethiopia",
      "Falkland Islands (the) (Malvinas)",
      "Faroe Islands (the)",
      "Fiji",
      "Finland",
      "France",
      "French Guiana",
      "French Polynesia (French Pacific Islands)",
      "French Southern Territories (the)",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Gibraltar",
      "Greece",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Heard Island and McDonald Islands",
      "Holy See (the)",
      "Honduras",
      "Hong Kong",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran (Islamic Republic of)",
      "Iraq",
      "Ireland (Eire)",
      "Isle of Man",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jersey",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Korea (the Democratic People's Republic of)",
      "Korea (the Republic of)",
      "Kuwait",
      "Kyrgyzstan",
      "Laos People's Democratic Republic (the)",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macau",
      "Macedonia (the former Yugoslav Republic of)",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands (the)",
      "Martinique",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Micronesia (Federated States of)",
      "Moldova (the Republic of)",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Montserrat",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands (the)",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger (the)",
      "Nigeria",
      "Niue",
      "Norfolk Island",
      "Northern Mariana Islands (the)",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines (the)",
      "Pitcairn Islands",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Réunion",
      "Romania",
      "Russia (the Russian Federation)",
      "Rwanda",
      "São Tome and Principe",
      "Saint Helena, Ascension and Tristan da Cunha",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Pierre and Miquelon",
      "Saint Vincent and The Grenadines",
      "Saint-Martin",
      "Samoa",
      "San Marino",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Sint Maarten (Dutch part)",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Georgia and the South Sandwich Islands",
      "Spain",
      "Sri Lanka",
      "Sudan (the)",
      "Suriname",
      "Svalbard and Jan Mayen",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syria (Syrian Arab Republic)",
      "Taiwan (Republic of China)",
      "Tajikistan",
      "Tanzania, United Republic of",
      "Thailand",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks and Caicos Islands",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates (the)",
      "United Kingdom of Great Britain and Northern Ireland (the)",
      "United States Minor Outlying Islands (the)",
      "Uruguay",
      "Virgin Islands  (U.S.)",
      "Uzbekistan",
      "Vanuatu",
      "Venezuela (Bolivarian Republic of)",
      "Vietnam",
      "Virgin Islands (British)",
      "Wallis and Futuna",
      "Western Sahara",
      "Yemen",
      "Zambia",
      "Zimbabwe",
      "Åland Islands",
      "Kosovo",
      "Saint Barthélemy",
      "South Sudan",
    ]),
    Schema.Null,
  ]),
  MemberDesignation: Schema.Union([
    Schema.Array(
      Schema.Literals([
        "Accredited Buyer Representative",
        "Accredited Buyer Representative Manager",
        "At Home With Diversity Certification",
        "Accredited Land Consultant",
        "Accredited Residential Manager®",
        "Associate Reserve Planner",
        "Certified Commercial Investment Member",
        "Certified International Property Specialist",
        "Certified Leasing Officer",
        "Certified Manager of Condominiums",
        "Certified Property Manager®",
        "Certified Real Estate Specialist",
        "Certified Real Estate Brokerage Manager",
        "Counselor of Real Estate",
        "Certified in Real Estate Finance",
        "Certified Reserve Planner",
        "Certified Residential Specialist®",
        "Certified Residential  Underwriter",
        "REALTOR e-PRO®",
        "Fellow of the Real Estate Institute",
        "Fellow of the Real Estate Institute (Appraisal Specialist)",
        "Fellow of the Real Estate Institute (Executive)",
        "General Accredited Appraiser",
        "Graduate REALTOR® Institute",
        "Performance Management Network",
        "Residential Accredited Appraiser",
        "REALTOR® Association Certified Executive",
        "Real Estate Professional Assistant",
        "Accredited Appraiser Canadian Institute",
        "Market Value Appraiser-Residential",
        "Accredited Leasing Officer",
        "Accredited Mortgage Professional",
        "Accredited Senior Appraiser",
        "Certified Valuation Analyst",
        "Certified Mold Remediation",
        "Certified Professional Residential Property Manager",
        "Canadian Residential Appraiser",
        "Fellows of the Royal Institution of Chartered Surveyors",
        "Member, Appraisal Institute",
        "Professional Land Economist",
        "Real Property Administrator®",
        "Society of Industrial and Office REALTORS®",
        "Senior Residential Appraiser",
        "Canadian Employee Relocation Professional",
        "Canadian Employee Relocation Council Relocation Specialist™",
        "Relocation Resort Specialist",
        "Seniors Real Estate Specialist",
        "Certified Lease Professional Designation",
        "Designated Agency Representatives",
        "Distinguished Real Estate Instructor™",
        "Unknown",
        "Certified Condo Specialist",
        "Canadian REALTOR® Association Executive",
        "NAR's Green Designation",
        "ACCREDITED GREENAGENT® -Residential",
        "ACCREDITED GREENBROKER® - Commercial",
        "EcoBroker®",
        "Transnational Referral Certified",
        "Certified Negotiation Expert",
        "Member of the Royal Institute of Charter Surveyors",
        "Certified Reserve Fund Planner",
        "Accredited Staging Professional",
        "Resort & Second-Home Property Specialist",
        "Short Sales and Foreclose Resource",
        "Business Corporation Owned by a Real Estate Broker",
        "Canadian Personal Property Appraiser",
        "Seller Representative Specialist",
        "Accredited Senior Agent",
        "Certified Luxury Home Marketing Specialist",
        "Royal Institute of Chartered Surveyors",
        "Accredited Commercial Professional",
        "Master Certified Negotiation Expert",
        "Associate of the Canadian Condominium Institute",
        "Real Estate Negotiation Expert",
        "Military Relocation Professional",
        "Pricing Strategy Advisor",
        "Accredited Luxury Home Specialist",
        "Performance Management Network Designation",
        "Certified in Marketing of Real Estate",
        "Residential Construction Certified",
        "Certified New Home Specialist",
        "Chartered Accountant",
        "Chartered Professional Accountant",
        "Certified General Accountant",
        "Certified Management Accountant",
        "BoundaryWise",
        "Chartered Financial Analyst",
        "National Commercial Real Estate Advisor",
        "Certified Real Estate Investment Planning Specialist",
        "Openn Certified Agent",
        "Accredited Real Estate Negotiator",
        "Luxury Homes Certification",
        "Canadian National Association Of Real Estate Appraisers",
        "Certified Real Estate Team Specialist",
        "Certified Consultant on Aging",
        "Certified Buyer Agent Expert",
        "Accredited Commercial Manager",
        "Canadian Certified Green Representative (CCGR)",
        "Real Estate Sector Governance Designation",
      ]),
    ),
    Schema.Null,
  ]),
  MemberLanguages: Schema.Union([
    Schema.Array(
      Schema.Literals([
        "Afrikaans",
        "Albanian",
        "American Sign Language (ASL)",
        "Arabic",
        "Armenian",
        "Bangla",
        "Bulgarian",
        "Burmese",
        "Chinese (Cantonese)",
        "Chinese (Mandarin)",
        "Cree",
        "Croatian",
        "Czech",
        "Danish",
        "Dari",
        "Dutch",
        "English",
        "Farsi",
        "Finnish",
        "French",
        "German",
        "Greek",
        "Gujarati",
        "Hebrew",
        "Hindi",
        "Hungarian",
        "Inuktitut (Inuit)",
        "Italian",
        "Japanese",
        "Korean",
        "Latvian",
        "Lithuanian",
        "Macedonian",
        "Maltese",
        "Malaysian",
        "Norwegian",
        "Pashto",
        "Persian",
        "Polish",
        "Portuguese",
        "Punjabi",
        "Romanian",
        "Russian",
        "Serbian",
        "Slovak",
        "Slovenian",
        "Spanish",
        "Swedish",
        "Tagalog (Filipino)",
        "Tamil",
        "Turkish",
        "Ukrainian",
        "Urdu",
        "Vietnamese",
        "Aboriginal languages",
        "Amharic",
        "Azeri",
        "Bahasa Malaysia",
        "Belorussian",

        "Catalan",
        "Creole",
        "Estonian",
        "Flemish",
        "Friesian",
        "Galla",
        "Gan",
        "Georgian",
        "Hakka",
        "Hausa",
        "Icelandic",
        "Indonesian",
        "Javanese",
        "Jin-yu",
        "Kannada",
        "Kazakh",
        "Kejia",
        "Khmer",
        "Kiswahili",
        "Konkani",
        "Kurdish",
        "Lao",
        "Luxembourgish",
        "Malagasy",
        "Malay",
        "Malayalam",
        "Marathi",
        "Miny",
        "Mongolian",
        "Pakhto",
        "Serbo-Croatian",
        "Sindhi",
        "Sinhala",
        "Somali",
        "Sunda",
        "Tchi",
        "Telugu",
        "Thai",
        "Tigrinya",
        "Uzbek",
        "Xiang",
        "Yiddish",
        "Yue",
        "Tajik",
        "Chaldean",
        "Assyrian",
        "Filipino",
        "Yoruba",
        "Igbo",
      ]),
    ),
    Schema.Null,
  ]),
  MemberSocialMedia: Schema.Union([
    Schema.Array(
      Schema.Struct({
        SocialMediaKey: Schema.NullOr(Schema.String),
        ResourceRecordKey: Schema.NullOr(Schema.String),
        SocialMediaType: Schema.NullOr(SocialMediaTypeSchema),
        ModificationTimestamp: Schema.DateTimeUtcFromString,
        ResourceName: Schema.NullOr(ResourceNameSchema),
        SocialMediaUrlOrId: Schema.NullOr(Schema.String),
      }),
    ),
    Schema.Null,
  ]),
  Media: Schema.NullOr(MediaSchema),
  MemberStateOrProvince: Schema.Union([
    Schema.Literals([
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland & Labrador",
      "Northwest Territories",
      "Nova Scotia",
      "Nunavut",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Yukon",
    ]),
    Schema.Null,
  ]),
  MemberStatus: Schema.Union([
    Schema.Literals(["Active", "Inactive"]),
    Schema.Null,
  ]),
  MemberType: Schema.Union([
    Schema.Literals([
      "Broker",
      "Non-MLS®",
      "Salesperson",
      "Firm",
      "Affiliate",
      "Affiliate Monthly",
      "Franchisor",
      "Guest",
      "Honourary",
      "Broker Life Member",
      "Salesperson Life Member",
      "Unknown",
      "Affiliate Bi-Annual",
      "Interboard",
      "Professional Affiliate",
      "Social Affiliate",
      "Dual",
      "Member",
    ]),
    Schema.Null,
  ]),
  MemberEmailYN: Schema.Union([Schema.Boolean, Schema.Null]),
});

export const MemberResponseSchema = ODataListEnvelopeSchema(MemberSchema);

export const MemberLanguageSubtagSchema = Schema.Struct({
  Afrikaans: Schema.Literal("af"),
  Albanian: Schema.Literal("sq"),
  Arabic: Schema.Literal("ar"),
  Armenian: Schema.Literal("hy"),
  Bangla: Schema.Literal("bn"),
  Bulgarian: Schema.Literal("bg"),
  Burmese: Schema.Literal("my"),
  "Chinese (Cantonese)": Schema.Literal("yue"),
  "Chinese (Mandarin)": Schema.Literal("cmn"),
  Cree: Schema.Literal("cr"),
  Croatian: Schema.Literal("hr"),
  Czech: Schema.Literal("cs"),
  Danish: Schema.Literal("da"),
  Dari: Schema.Literal("prs"),
  Dutch: Schema.Literal("nl"),
  English: Schema.Literal("en"),
  Finnish: Schema.Literal("fi"),
  French: Schema.Literal("fr"),
  German: Schema.Literal("de"),
  Gujarati: Schema.Literal("gu"),
  Hebrew: Schema.Literal("he"),
  Hindi: Schema.Literal("hi"),
  Hungarian: Schema.Literal("hu"),
  Italian: Schema.Literal("it"),
  Japanese: Schema.Literal("ja"),
  Korean: Schema.Literal("ko"),
  Latvian: Schema.Literal("lv"),
  Lithuanian: Schema.Literal("lt"),
  Macedonian: Schema.Literal("mk"),
  Maltese: Schema.Literal("mt"),
  Norwegian: Schema.Literal("no"),
  Pashto: Schema.Literal("ps"),
  Persian: Schema.Literal("fa"),
  Polish: Schema.Literal("pl"),
  Portuguese: Schema.Literal("pt"),
  Punjabi: Schema.Literal("pa"),
  Romanian: Schema.Literal("ro"),
  Russian: Schema.Literal("ru"),
  Serbian: Schema.Literal("sr"),
  Slovak: Schema.Literal("sk"),
  Slovenian: Schema.Literal("sl"),
  Spanish: Schema.Literal("es"),
  Swedish: Schema.Literal("sv"),
  Tamil: Schema.Literal("ta"),
  Turkish: Schema.Literal("tr"),
  Ukrainian: Schema.Literal("uk"),
  Urdu: Schema.Literal("ur"),
  Vietnamese: Schema.Literal("vi"),
  Amharic: Schema.Literal("am"),
  Catalan: Schema.Literal("ca"),
  Estonian: Schema.Literal("et"),
  Flemish: Schema.Literal("nl"),
  Georgian: Schema.Literal("ka"),
  Hausa: Schema.Literal("ha"),
  Icelandic: Schema.Literal("is"),
  Indonesian: Schema.Literal("id"),
  Javanese: Schema.Literal("jv"),
  Kannada: Schema.Literal("kn"),
  Kazakh: Schema.Literal("kk"),
  Khmer: Schema.Literal("km"),
  Kiswahili: Schema.Literal("sw"),
  Kurdish: Schema.Literal("ku"),
  Lao: Schema.Literal("lo"),
  Luxembourgish: Schema.Literal("lb"),
  Malagasy: Schema.Literal("mg"),
  Malayalam: Schema.Literal("ml"),
  Marathi: Schema.Literal("mr"),
  Mongolian: Schema.Literal("mn"),
  "Serbo-Croatian": Schema.Literal("sh"),
  Sindhi: Schema.Literal("sd"),
  Sinhala: Schema.Literal("si"),
  Somali: Schema.Literal("so"),
  Telugu: Schema.Literal("te"),
  Thai: Schema.Literal("th"),
  Tigrinya: Schema.Literal("ti"),
  Uzbek: Schema.Literal("uz"),
  Yiddish: Schema.Literal("yi"),
  Tajik: Schema.Literal("tg"),
  Filipino: Schema.Literal("fil"),
  Yoruba: Schema.Literal("yo"),
  Igbo: Schema.Literal("ig"),
  Farsi: Schema.Literal("fa"),
  Greek: Schema.Literal("el"),
  "Inuktitut (Inuit)": Schema.Literal("iu"),
  Malaysian: Schema.Literal("ms"),
  "Tagalog (Filipino)": Schema.Literal("tl"),
  "Aboriginal languages": Schema.Literal("aus"),
  Azeri: Schema.Literal("az"),
  "Bahasa Malaysia": Schema.Literal("ms"),
  Belorussian: Schema.Literal("be"),
  Belarusian: Schema.Literal("be"),
  Creole: Schema.Literal("ht"),
  Friesian: Schema.Literal("fy"),
  Galla: Schema.Literal("om"),
  Gan: Schema.Literal("gan"),
  Hakka: Schema.Literal("hak"),
  "Jin-yu": Schema.Literal("cjy"),
  Kejia: Schema.Literal("hak"),
  Konkani: Schema.Literal("kok"),
  Malay: Schema.Literal("ms"),
  Miny: Schema.Literal("nan"),
  Pakhto: Schema.Literal("ps"),
  Sunda: Schema.Literal("su"),
  Tchi: Schema.Literal("tw"),
  Xiang: Schema.Literal("hsn"),
  Yue: Schema.Literal("yue"),
  Chaldean: Schema.Literal("cld"),
  Assyrian: Schema.Literal("aii"),
});
