import { DateTime, Schema } from "effect";

export const RoomsSchema = Schema.Array(
  Schema.Struct({
    RoomKey: Schema.String.annotate({
      message: "Value is invalid for RoomKey.",
      description: "A unique identifier for this record.",
      title: "Room Key",
      identifier: "RoomKey",
      examples: ["1525032059", "1525032245", "1543188404"],
    }),
    ListingId: Schema.Union([Schema.String, Schema.Null]).annotate({
      message: "Value is invalid for ListingId.",
      description:
        "This is the foreign ID relating to the Property Resource. The well known identifier for the listing.",
      title: "Listing Id",
      identifier: "ListingId",
      examples: ["X9465223", "SK015977", "X12348197"],
    }),
    ListingKey: Schema.String.annotate({
      message: "Value is invalid for ListingKey.",
      description:
        "This is the foreign key relating to the property resource. A unique identifier for this record from the immediate source.",
      title: "Listing Key",
      identifier: "ListingKey",
      examples: ["26034183", "26507412", "26935822"],
    }),
    ModificationTimestamp: Schema.DateTimeUtcFromString.annotate({
      message: "Value is invalid for ModificationTimestamp.",
      description:
        "Date/time this record was last modified (in Zulu time (UTC)).",
      title: "Modification Timestamp",
      identifier: "ModificationTimestamp",
      examples: [
        DateTime.makeUnsafe("2025-10-28T00:34:46.690Z"),
        DateTime.makeUnsafe("2025-12-01T16:55:25.400Z"),
        DateTime.makeUnsafe("2025-10-28T00:34:48.550Z"),
      ],
    }),
    RoomDescription: Schema.Union([Schema.String, Schema.Null]).annotate({
      message: "Value is invalid for RoomDescription.",
      description: "A textual description of the given room.",
      title: "Room Description",
      identifier: "RoomDescription",
    }),
    RoomDimensions: Schema.Union([Schema.String, Schema.Null]).annotate({
      message: "Value is invalid for RoomDimensions.",
      description: "A textual description of the dimensions of the given room.",
      title: "Room Dimensions",
      identifier: "RoomDimensions",
    }),
    RoomLength: Schema.Union([Schema.Number, Schema.Null]).annotate({
      message: "Value is invalid for RoomLength.",
      description:
        "A numeric representation of the length of the given room. See the RoomLengthWidthUnits for the unit of measurement used for the length and width.",
      title: "Room Length",
      identifier: "RoomLength",
      examples: [3.86, 3.17, 2.69, 1.82],
    }),
    RoomLevel: Schema.Union([
      Schema.Literals([
        "Second level",
        "Third level",
        "Fourth level",
        "Fifth level",
        "Above",
        "Basement",
        "Flat",
        "Lower level",
        "Main level",
        "Other",
        "Sub-basement",
        "Upper Level",
        "Unknown",
        "Ground level",
        "In between",
        "Loft",
        "Sixth Level",
        "Additional Accommodation",
        "Auxiliary Building",
        "Secondary Dwelling Unit",
      ]),
      Schema.Null,
    ]).annotate({
      message: "Value is invalid for RoomLevel.",
      description:
        "The level within the dwelling on which the given room is located.",
      title: "Room Level",
      identifier: "RoomLevel",
      examples: ["Main level", "Second level", "Fourth level"],
    }),
    RoomWidth: Schema.Union([Schema.Number, Schema.Null]).annotate({
      message: "Value is invalid for RoomWidth.",
      description: "A numeric representation of the width of the given room.",
      title: "Room Width",
      identifier: "RoomWidth",
      examples: [3.86, 4.57, 3.86, 5.05, 1.52],
    }),
    RoomLengthWidthUnits: Schema.Union([
      Schema.Literals(["meters", "feet"]),
      Schema.Null,
    ]).annotate({
      message: "Value is invalid for RoomLengthWidthUnits.",
      description:
        "The unit of measurement used for the value in the RoomLength and the RoomWidth fields. e.g. feet, meters, etc.",
      title: "Room Length Width Units",
      identifier: "RoomLengthWidthUnits",
      examples: ["feet", "meters"],
    }),
    RoomType: Schema.Union([
      Schema.Literals([
        "Living room",
        "Dining room",
        "Kitchen",
        "Family room",
        "Den",
        "Family bathroom",
        "Primary Bedroom",
        "Bedroom 2",
        "Bedroom 3",
        "Bedroom 4",
        "Bedroom 5",
        "Bedroom 6",
        "Laundry room",
        "Partial bathroom",
        "Additional bedroom",
        "Conservatory",
        "Eating area",
        "Full bathroom",
        "Full ensuite bathroom",
        "Foyer",
        "Storage",
        "Hobby room",
        "Partial ensuite bathroom",
        "Recreational, Games room",
        "Enclosed porch",
        "Workshop",
        "Utility room",
        "Solarium",
        "Living room/Dining room",
        "Addition",
        "Atrium",
        "Bath (# pieces 1-6)",
        "Bedroom",
        "Cold room",
        "Dinette",
        "Dining nook",
        "Ensuite (# pieces 2-6)",
        "Great room",
        "Jacuzzi",
        "Kitchen/Dining room",
        "Loft",
        "Mud room",
        "Other",
        "Sauna",
        "Library",
        "1pc Bathroom",
        "2pc Bathroom",
        "3pc Bathroom",
        "4pc Bathroom",
        "5pc Bathroom",
        "6pc Bathroom",
        "1pc Ensuite bath",
        "2pc Ensuite bath",
        "3pc Ensuite bath",
        "4pc Ensuite bath",
        "5pc Ensuite bath",
        "6pc Ensuite bath",
        "Steam room",
        "Party room",
        "Office",
        "In-law suite",
        "Rental unit",
        "Guest suite",
        "Sunroom",
        "Attic (finished)",
        "Playroom",
        "Games room",
        "Balcony",
        "Fruit cellar",
        "Florida/Fireplace",
        "Florida room",
        "Family room/Fireplace",
        "Living room/Fireplace",
        "Porch",
        "Sunroom/Fireplace",
        "Sitting room",
        "Eat in kitchen",
        "Recreation room",
        "Gym",
        "Exercise room",
        "Ensuite",
        "Inlaw suite",
        "Multi-use room",
        "Lunchroom",
        "Mezzanine",
        "Not known",
        "Flat",
        "Breakfast",
        "Nursery",
        "Furnace",
        "Pantry",
        "Study",
        "Beverage room",
        "Bathroom",
        "Attic",
        "Walk Up Attic",
        "Muskoka Room",
        "Music",
        "Media",
        "Wine Cellar",
        "Bedroom - Bachelor",
        "Hall",
        "Lobby",
        "Roughed-In Bathroom",
        "Computer Room",
        "Bonus Room",
        "Photography-dark room",
        "Second Kitchen",
        "Laundry / Bath",
        "Flex Space",
        "Patio",
        "Indoor Pool Room",
        "Entrance",
        "Studio",
        "Unfinished Room",
      ]),
      Schema.Null,
    ]).annotate({
      message: "Value is invalid for RoomType.",
      description:
        "The type of room being described by the other fields in the PropertyRooms resource.",
      title: "Room Type",
      examples: ["Bathroom", "Bedroom", "Living room", "Primary Bedroom"],
      identifier: "RoomType",
    }),
  }),
);

export type RoomsType = typeof RoomsSchema.Type;
